
export const bodyParts = [
  {
    name: "Shoulder",
    image: require("../assets/images/back.png"),
  },
  {
    name: "Lower Back",
    image: require("../assets/images/chest.png"),
  },
  {
    name: "Biceps Arms Without Equipment",
    image: require("../assets/images/neck.png"),
  },
  {
    name: "Biceps Arms With Equipment",
    image: require("../assets/images/shoulders.png"),
  },
  {
    name: "Triceps Arms Without Equipment",
    image: require("../assets/images/upperLegs.png"),
  },
  {
    name: "Triceps Arms With Equipment",
    image: require("../assets/images/upperLegs.png"),
  },
  {
    name: "Bulgarian Split Squats",
    image: require("../assets/images/upperLegs.png"),
  },
  {
    name: "Hip Thrusts",
    image: require("../assets/images/upperLegs.png"),
  },
  {
    name: "Standing Calf Raises",
    image: require("../assets/images/upperLegs.png"),
  },
  {
    name: "Barbell Shoulder",
    image: require("../assets/images/upperLegs.png"),
  },
  {
    name: "Lateral Raises",
    image: require("../assets/images/upperLegs.png"),
  },
  {
    name: "Six Pack",
    image: require("../assets/images/waist.png"),
  },
];

export const exercisesData = [
  //Shoulder
  {
    bodyPart: "Shoulder",
    equipment: " cablesd ",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/Incline-shoulder-press.gif",
    id: "0001",
    instructions: [
      "Sit on the cable machine with your back straight and feet flat on the ground.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Incline Shoulder Press ",
    secondaryMuscles: " rhomceboids ",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "body weight",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/Lateral%20Raises.gif",
    id: "0002",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
      "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
      "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
      "Alternate sides with each repetition.",
    ],
    name: "Lateral Raises",
    secondaryMuscles: "bicfdeeps",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverage machine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/arnold-press.gif",
    id: "0003",
    instructions: [
      "Adjust the machine to your desired weight and height.",
      "Place your hands on the parallel bars with a close grip, palms facing each other.",
      "Hang from the bars with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the bars.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Arnold Press",
    secondaryMuscles: "bicfeeps",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverage machisne",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/bird-sitting-on-a-bench.gif",
    id: "0004",
    instructions: [
      "Adjust the machine to your desired weight and height settings.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the handles.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Bird Sitting On A Bench",
    secondaryMuscles: "fornhearms",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverage macshijne",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/bird-with-elastic.gif",
    id: "0005",
    instructions: [
      "Adjust the machine to your desired assistance level.",
      "Stand on the foot platform and grip the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Keep your chest up and shoulders back, engage your core, and slightly bend your knees.",
      "Pull your body up by flexing your elbows and driving your elbows down towards your sides.",
      "Continue pulling until your chin is above the bar.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Bird With Elastic",
    secondaryMuscles: "forerwearms",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverage kmachine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/chin-pull-with-elastic.gif",
    id: "0006",
    instructions: [
      "Adjust the machine to your desired weight and height settings.",
      "Stand facing the machine with your feet shoulder-width apart.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your lats and biceps, and pull yourself up towards the handles.",
      "Pause for a moment at the top, squeezing your back muscles.",
      "Slowly lower yourself back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Chin Pull With Elastic",
    secondaryMuscles: "fodfrearms",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "stabsility ball",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/chin-pull-with-kettlebell.gif",
    id: "0007",
    instructions: [
      "Place the stability ball on the ground and lie face down on top of it, with your hips resting on the ball and your feet against a wall or other stable surface.",
      "Position your hands behind your head or crossed over your chest.",
      "Engage your core and slowly lift your upper body off the ball, extending your back until your body forms a straight line from your head to your heels.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Chin Pull With Kettlebell",
    secondaryMuscles: "hamsfggtringss",
    target: "spine",
  },
  {
    bodyPart: "Shoulder",
    equipment: "bodsway weight",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/cuban-rotations.gif",
    id: "0008",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "Bend your knees and tuck them towards your chest.",
      "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.",
      "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Cuban Rotations",
    secondaryMuscles: "forearmdws",
    target: "upper back",
  },
  {
    bodyPart: "Shoulder",
    equipment: "basody weight",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/externally-rotate-the-shoulder-at-the-pulley.gif",
    id: "0009",
    instructions: [
      "Stand tall with your feet shoulder-width apart.",
      "Extend your arms straight out in front of you, parallel to the ground.",
      "Cross your arms in front of your body, with your right arm over your left arm.",
      "Interlock your fingers and rotate your palms away from your body.",
      "Slowly raise your arms up and away from your body, feeling a stretch in your back and chest.",
      "Hold the stretch for 15-30 seconds, then release.",
      "Repeat on the opposite side.",
    ],
    name: "Externally Rotate The Shoulder At The Pulley",
    secondaryMuscles: "chest",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "band",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/frontal-elevations.gif",
    id: "0010",
    instructions: [
      "Attach the band to a pull-up bar or sturdy anchor point.",
      "Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.",
      "Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.",
      "Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Frontal Elevations",
    secondaryMuscles: "forearwerr",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "cabcle",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/guided-bar-chin-pull.gif",
    id: "0011",
    instructions: [
      "Sit on the cable machine with your back straight and feet flat on the ground.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Guided Bar Chin Pull",
    secondaryMuscles: "rhomboivbd",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "bodedy weight",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/guided-bar-neck-press.gif",
    id: "0013",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
      "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
      "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
      "Alternate sides with each repetition.",
    ],
    name: "Guided Bar Neck Press",
    secondaryMuscles: "forearpoi",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverage magchine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/handstand-push-up.gif",
    id: "0014",
    instructions: [
      "Adjust the machine to your desired weight and height.",
      "Place your hands on the parallel bars with a close grip, palms facing each other.",
      "Hang from the bars with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the bars.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Handstand Push Up",
    secondaryMuscles: "forelarml",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverage macgdhine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/horizontal-shoulder-extensions-with-elastic.gif",
    id: "0015",
    instructions: [
      "Adjust the machine to your desired weight and height settings.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the handles.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Horizontal Shoulder Extensions With Elastic",
    secondaryMuscles: "forearwew",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverage vmachine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/inclined-dumbbell-lateral-raises.gif",
    id: "0016",
    instructions: [
      "Adjust the machine to your desired assistance level.",
      "Stand on the foot platform and grip the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Keep your chest up and shoulders back, engage your core, and slightly bend your knees.",
      "Pull your body up by flexing your elbows and driving your elbows down towards your sides.",
      "Continue pulling until your chin is above the bar.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Inclined Dumbbell Lateral Raises",
    secondaryMuscles: "forearvbf",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverage emachine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/inverted-bird-with-suspension-straps.gif",
    id: "0017",
    instructions: [
      "Adjust the machine to your desired weight and height settings.",
      "Stand facing the machine with your feet shoulder-width apart.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your lats and biceps, and pull yourself up towards the handles.",
      "Pause for a moment at the top, squeezing your back muscles.",
      "Slowly lower yourself back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Inverted Bird With Suspension Straps",
    secondaryMuscles: "forearxcs",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "stability ball",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/iron-cross-with-dumbbells.gif",
    id: "0018",
    instructions: [
      "Place the stability ball on the ground and lie face down on top of it, with your hips resting on the ball and your feet against a wall or other stable surface.",
      "Position your hands behind your head or crossed over your chest.",
      "Engage your core and slowly lift your upper body off the ball, extending your back until your body forms a straight line from your head to your heels.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Iron Cross With Dumbbells",
    secondaryMuscles: "haxmstrings",
    target: "spine",
  },
  {
    bodyPart: "Shoulder",
    equipment: "body wevdight",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/kettlebell-lateral-raises.gif",
    id: "0019",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "Bend your knees and tuck them towards your chest.",
      "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.",
      "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Kettlebell Lateral Raises",
    secondaryMuscles: "core",
    target: "upper back",
  },
  {
    bodyPart: "Shoulder",
    equipment: "cable",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/kettlebell-thrusters.gif",
    id: "0020",
    instructions: [
      "Sit on the cable machine with your back straight and feet flat on the ground.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Kettlebell Thrusters",
    secondaryMuscles: "rhombovier",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "bxody weight",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/landmine-press.gif",
    id: "0021",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
      "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
      "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
      "Alternate sides with each repetition.",
    ],
    name: "Landmine Press",
    secondaryMuscles: "forearcf",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverasge machine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/lateral-elevations%20with-landmine.gif",
    id: "0022",
    instructions: [
      "Adjust the machine to your desired weight and height.",
      "Place your hands on the parallel bars with a close grip, palms facing each other.",
      "Hang from the bars with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the bars.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Lateral Elevations With Landmine",
    secondaryMuscles: "forearpo",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "bandx",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/lateral-raises-on-the-machine.gif",
    id: "0023",
    instructions: [
      "Attach the band to a pull-up bar or sturdy anchor point.",
      "Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.",
      "Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.",
      "Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Lateral Raises On The Machine",
    secondaryMuscles: "forearmko",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "cablde",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/low-pulley-front-raises.gif",
    id: "0024",
    instructions: [
      "Sit on the cable machine with your back straight and feet flat on the ground.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Low Pulley Front Raises",
    secondaryMuscles: "rhomboivn",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "bwssody weight",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/military-press.gif",
    id: "0025",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
      "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
      "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
      "Alternate sides with each repetition.",
    ],
    name: "Military Press",
    secondaryMuscles: "forearmqw",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leveragnge machine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/pull-face.gif",
    id: "0026",
    instructions: [
      "Adjust the machine to your desired weight and height.",
      "Place your hands on the parallel bars with a close grip, palms facing each other.",
      "Hang from the bars with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the bars.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Pull Face",
    secondaryMuscles: "foreabrvb",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leveragrfe machine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/pulley-lateral-raises.gif",
    id: "0027",
    instructions: [
      "Adjust the machine to your desired weight and height settings.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the handles.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Pulley Lateral Raises",
    secondaryMuscles: "forearmaw",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "levervfage machine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/reverse-pec-deck.gif",
    id: "0028",
    instructions: [
      "Adjust the machine to your desired assistance level.",
      "Stand on the foot platform and grip the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Keep your chest up and shoulders back, engage your core, and slightly bend your knees.",
      "Pull your body up by flexing your elbows and driving your elbows down towards your sides.",
      "Continue pulling until your chin is above the bar.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Reverse Pec Deck",
    secondaryMuscles: "forearmxc",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "breand",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/seated-shoulder-press-with-elastic.gif",
    id: "0029",
    instructions: [
      "Attach the band to a pull-up bar or sturdy anchor point.",
      "Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.",
      "Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.",
      "Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Seated Shoulder Press With Elastic",
    secondaryMuscles: "forearmdf",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "cabbsle",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/shoulder-external-rotations.gif",
    id: "0030",
    instructions: [
      "Sit on the cable machine with your back straight and feet flat on the ground.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Shoulder External Rotations",
    secondaryMuscles: "rhomboiddf",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "boferdy weight",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/shoulder-press-on-the-machine.gif",
    id: "0031",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
      "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
      "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
      "Alternate sides with each repetition.",
    ],
    name: "Shoulder Press On The Machine",
    secondaryMuscles: "foreaxcx",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "levermhjage machine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/shoulder-press-on-the-smith-machine.gif",
    id: "0032",
    instructions: [
      "Adjust the machine to your desired weight and height.",
      "Place your hands on the parallel bars with a close grip, palms facing each other.",
      "Hang from the bars with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the bars.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Shoulder Press On The Smith Machine",
    secondaryMuscles: "foreacvv",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "levedwsrage machine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/shoulder-press-with-dumbbells.gif",
    id: "0033",
    instructions: [
      "Adjust the machine to your desired weight and height settings.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the handles, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the handles.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Shoulder Press With Dumbbells",
    secondaryMuscles: "foreadfg",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leveragedw machine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/shoulder-press-with-elastic.gif",
    id: "0034",
    instructions: [
      "Adjust the machine to your desired assistance level.",
      "Stand on the foot platform and grip the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Keep your chest up and shoulders back, engage your core, and slightly bend your knees.",
      "Pull your body up by flexing your elbows and driving your elbows down towards your sides.",
      "Continue pulling until your chin is above the bar.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Shoulder Press With Elastic",
    secondaryMuscles: "forearfd",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leverage macbfhine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/shoulder-press-with-kettlebell.gif",
    id: "0035",
    instructions: [
      "Adjust the machine to your desired weight and height settings.",
      "Stand facing the machine with your feet shoulder-width apart.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your lats and biceps, and pull yourself up towards the handles.",
      "Pause for a moment at the top, squeezing your back muscles.",
      "Slowly lower yourself back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Shoulder Press With Kettlebell",
    secondaryMuscles: "forearmaa",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "stabilitcvy ball",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/thruster-with-landmine.gif",
    id: "0036",
    instructions: [
      "Place the stability ball on the ground and lie face down on top of it, with your hips resting on the ball and your feet against a wall or other stable surface.",
      "Position your hands behind your head or crossed over your chest.",
      "Engage your core and slowly lift your upper body off the ball, extending your back until your body forms a straight line from your head to your heels.",
      "Pause for a moment at the top, then slowly lower your upper body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Thruster With Landmine",
    secondaryMuscles: "gluctes",
    target: "spine",
  },
  {
    bodyPart: "Shoulder",
    equipment: "body weiadght",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/thruster.gif",
    id: "0037",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "Bend your knees and tuck them towards your chest.",
      "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.",
      "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Thruster",
    secondaryMuscles: "bicneps",
    target: "upper back",
  },
  {
    bodyPart: "Shoulder",
    equipment: "cavedble",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/toe-push-ups.gif",
    id: "0038",
    instructions: [
      "Sit on the cable machine with your back straight and feet flat on the ground.",
      "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
      "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
      "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Toe Push Ups",
    secondaryMuscles: "rhomboids",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "boxsfdy weight",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/unilateral-pulley-lateral-raises.gif",
    id: "0039",
    instructions: [
      "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
      "Engage your core and pull your shoulder blades down and back.",
      "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
      "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
      "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
      "Alternate sides with each repetition.",
    ],
    name: "Unilateral Pulley Lateral Raises",
    secondaryMuscles: "fornearm",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "leveragedge machine",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/unilateral-shoulder-press-on-the-landmine.gif",
    instructions: [
      "Adjust the machine to your desired weight and height.",
      "Place your hands on the parallel bars with a close grip, palms facing each other.",
      "Hang from the bars with your arms fully extended and your feet off the ground.",
      "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
      "Continue pulling until your chin is above the bars.",
      "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Unilateral Shoulder Press On The Landmine",
    secondaryMuscles: "forear",
    target: "lats",
  },
  {
    bodyPart: "Shoulder",
    equipment: "banhjd",
    gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Shoulder/unilateral-shoulder-press-with-elastic.gif",
    id: "0040",
    instructions: [
      "Attach the band to a pull-up bar or sturdy anchor point.",
      "Step onto the band and grip the bar with your palms facing away from you, hands slightly wider than shoulder-width apart.",
      "Hang with your arms fully extended, keeping your core engaged and your shoulders down and back.",
      "Pull your body up towards the bar by squeezing your shoulder blades together and driving your elbows down towards your hips.",
      "Continue pulling until your chin is above the bar, then slowly lower yourself back down to the starting position.",
      "Repeat for the desired number of repetitions.",
    ],
    name: "Unilateral Shoulder Press With Elastic",
    secondaryMuscles: "forea",
    target: "lats",
  },


  // // Lower Back
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/02271301-Cable-Standing-Fly_Chest-FIX_720.gif",
  //   id: "3297",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "Bend your knees and tuck them towards your chest.",
  //     "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.",
  //     "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "Lower Back",
  //   secondaryMuscles: "core",
  //   target: "upper back",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "cable",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00251301-Barbell-Bench-Press_Chest-FIX_720.gif",
  //   id: "0087",
  //   instructions: [
  //     "Sit on the cable machine with your back straight and feet flat on the ground.",
  //     "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
  //     "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "alternate lateral pulldown",
  //   secondaryMuscles: "rhomboids",
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00331301-Barbell-Decline-Bench-Press_Chest_720.gif",
  //   id: "3293",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
  //     "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
  //     "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
  //     "Alternate sides with each repetition.",
  //   ],
  //   name: "archer pull up",
  //   secondaryMuscles: "forearms",
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "leverage machine",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/01511301-Cable-Bench-Press_Chest-FIX_720.gif",
  //   id: "0415",
  //   instructions: [
  //     "Adjust the machine to your desired weight and height.",
  //     "Place your hands on the parallel bars with a close grip, palms facing each other.",
  //     "Hang from the bars with your arms fully extended and your feet off the ground.",
  //     "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
  //     "Continue pulling until your chin is above the bars.",
  //     "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "assisted parallel close grip pull-up",
  //   secondaryMuscles: "forearms",
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00331301-Barbell-Decline-Bench-Press_Chest_720.gif",
  //   id: "3293",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
  //     "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
  //     "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
  //     "Alternate sides with each repetition.",
  //   ],
  //   name: "archer pull up",
  //   secondaryMuscles: "forearms",
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "leverage machine",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/01511301-Cable-Bench-Press_Chest-FIX_720.gif",
  //   id: "0015",
  //   instructions: [
  //     "Adjust the machine to your desired weight and height.",
  //     "Place your hands on the parallel bars with a close grip, palms facing each other.",
  //     "Hang from the bars with your arms fully extended and your feet off the ground.",
  //     "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
  //     "Continue pulling until your chin is above the bars.",
  //     "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "assisted parallel close grip pull-up",
  //   secondaryMuscles: "biceps",
  //   target: "lats",
  // },

  // // Upper Arms Exercise Without Dumbbells
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "cable",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00251301-Barbell-Bench-Press_Chest-FIX_720.gif",
  //   id: "0087",
  //   instructions: [
  //     "Sit on the cable machine with your back straight and feet flat on the ground.",
  //     "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
  //     "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "alternate lateral pulldown",
  //   secondaryMuscles: ["biceps", "rhomboids"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00331301-Barbell-Decline-Bench-Press_Chest_720.gif",
  //   id: "3293",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
  //     "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
  //     "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
  //     "Alternate sides with each repetition.",
  //   ],
  //   name: "archer pull up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "leverage machine",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/01511301-Cable-Bench-Press_Chest-FIX_720.gif",
  //   id: "0015",
  //   instructions: [
  //     "Adjust the machine to your desired weight and height.",
  //     "Place your hands on the parallel bars with a close grip, palms facing each other.",
  //     "Hang from the bars with your arms fully extended and your feet off the ground.",
  //     "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
  //     "Continue pulling until your chin is above the bars.",
  //     "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "assisted parallel close grip pull-up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00331301-Barbell-Decline-Bench-Press_Chest_720.gif",
  //   id: "3293",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
  //     "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
  //     "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
  //     "Alternate sides with each repetition.",
  //   ],
  //   name: "archer pull up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "leverage machine",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/01511301-Cable-Bench-Press_Chest-FIX_720.gif",
  //   id: "0015",
  //   instructions: [
  //     "Adjust the machine to your desired weight and height.",
  //     "Place your hands on the parallel bars with a close grip, palms facing each other.",
  //     "Hang from the bars with your arms fully extended and your feet off the ground.",
  //     "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
  //     "Continue pulling until your chin is above the bars.",
  //     "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "assisted parallel close grip pull-up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },

  // //Upper Arms Exercise With Dumbbells
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/02271301-Cable-Standing-Fly_Chest-FIX_720.gif",
  //   id: "3297",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "Bend your knees and tuck them towards your chest.",
  //     "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.",
  //     "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "Lower Back",
  //   secondaryMuscles: ["biceps", "forearms", "core"],
  //   target: "upper back",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "cable",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00251301-Barbell-Bench-Press_Chest-FIX_720.gif",
  //   id: "0087",
  //   instructions: [
  //     "Sit on the cable machine with your back straight and feet flat on the ground.",
  //     "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
  //     "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "alternate lateral pulldown",
  //   secondaryMuscles: ["biceps", "rhomboids"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00331301-Barbell-Decline-Bench-Press_Chest_720.gif",
  //   id: "3293",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
  //     "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
  //     "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
  //     "Alternate sides with each repetition.",
  //   ],
  //   name: "archer pull up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "leverage machine",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/01511301-Cable-Bench-Press_Chest-FIX_720.gif",
  //   id: "0015",
  //   instructions: [
  //     "Adjust the machine to your desired weight and height.",
  //     "Place your hands on the parallel bars with a close grip, palms facing each other.",
  //     "Hang from the bars with your arms fully extended and your feet off the ground.",
  //     "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
  //     "Continue pulling until your chin is above the bars.",
  //     "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "assisted parallel close grip pull-up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00331301-Barbell-Decline-Bench-Press_Chest_720.gif",
  //   id: "3293",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
  //     "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
  //     "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
  //     "Alternate sides with each repetition.",
  //   ],
  //   name: "archer pull up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "leverage machine",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/01511301-Cable-Bench-Press_Chest-FIX_720.gif",
  //   id: "0015",
  //   instructions: [
  //     "Adjust the machine to your desired weight and height.",
  //     "Place your hands on the parallel bars with a close grip, palms facing each other.",
  //     "Hang from the bars with your arms fully extended and your feet off the ground.",
  //     "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
  //     "Continue pulling until your chin is above the bars.",
  //     "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "assisted parallel close grip pull-up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },

  // // Upper Arms Exercise With Cable Pull
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/02271301-Cable-Standing-Fly_Chest-FIX_720.gif",
  //   id: "3297",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, hands slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "Bend your knees and tuck them towards your chest.",
  //     "Slowly lift your legs up, keeping them straight, until your body is parallel to the ground.",
  //     "Hold this position for a few seconds, then slowly lower your legs back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "Lower Back",
  //   secondaryMuscles: ["biceps", "forearms", "core"],
  //   target: "upper back",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "cable",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00251301-Barbell-Bench-Press_Chest-FIX_720.gif",
  //   id: "0087",
  //   instructions: [
  //     "Sit on the cable machine with your back straight and feet flat on the ground.",
  //     "Grasp the handles with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Lean back slightly and pull the handles towards your chest, squeezing your shoulder blades together.",
  //     "Pause for a moment at the peak of the movement, then slowly release the handles back to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "alternate lateral pulldown",
  //   secondaryMuscles: ["biceps", "rhomboids"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00331301-Barbell-Decline-Bench-Press_Chest_720.gif",
  //   id: "3293",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
  //     "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
  //     "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
  //     "Alternate sides with each repetition.",
  //   ],
  //   name: "archer pull up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "leverage machine",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/01511301-Cable-Bench-Press_Chest-FIX_720.gif",
  //   id: "0015",
  //   instructions: [
  //     "Adjust the machine to your desired weight and height.",
  //     "Place your hands on the parallel bars with a close grip, palms facing each other.",
  //     "Hang from the bars with your arms fully extended and your feet off the ground.",
  //     "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
  //     "Continue pulling until your chin is above the bars.",
  //     "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "assisted parallel close grip pull-up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00331301-Barbell-Decline-Bench-Press_Chest_720.gif",
  //   id: "3293",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
  //     "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
  //     "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
  //     "Alternate sides with each repetition.",
  //   ],
  //   name: "archer pull up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "leverage machine",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/01511301-Cable-Bench-Press_Chest-FIX_720.gif",
  //   id: "0015",
  //   instructions: [
  //     "Adjust the machine to your desired weight and height.",
  //     "Place your hands on the parallel bars with a close grip, palms facing each other.",
  //     "Hang from the bars with your arms fully extended and your feet off the ground.",
  //     "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
  //     "Continue pulling until your chin is above the bars.",
  //     "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "assisted parallel close grip pull-up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "leverage machine",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/01511301-Cable-Bench-Press_Chest-FIX_720.gif",
  //   id: "0015",
  //   instructions: [
  //     "Adjust the machine to your desired weight and height.",
  //     "Place your hands on the parallel bars with a close grip, palms facing each other.",
  //     "Hang from the bars with your arms fully extended and your feet off the ground.",
  //     "Engage your back muscles and pull your body up towards the bars, keeping your elbows close to your body.",
  //     "Continue pulling until your chin is above the bars.",
  //     "Pause for a moment at the top, then slowly lower your body back down to the starting position.",
  //     "Repeat for the desired number of repetitions.",
  //   ],
  //   name: "assisted parallel close grip pull-up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
  // {
  //   bodyPart: "Lower Back",
  //   equipment: "body weight",
  //   gifUrl: "https://raw.githubusercontent.com/SSharma554/Data/main/Chest/00331301-Barbell-Decline-Bench-Press_Chest_720.gif",
  //   id: "3293",
  //   instructions: [
  //     "Start by hanging from a pull-up bar with an overhand grip, slightly wider than shoulder-width apart.",
  //     "Engage your core and pull your shoulder blades down and back.",
  //     "As you pull yourself up, bend one arm and bring your elbow towards your side, while keeping the other arm straight.",
  //     "Continue pulling until your chin is above the bar and your bent arm is fully flexed.",
  //     "Lower yourself back down with control, straightening the bent arm and repeating the movement on the other side.",
  //     "Alternate sides with each repetition.",
  //   ],
  //   name: "archer pull up",
  //   secondaryMuscles: ["biceps", "forearms"],
  //   target: "lats",
  // },
];
